### ISSUE TITLE
Module not found: Can't resolve '@babel/runtime/helpers/esm/extends'

### ISSUE THREAD

**Issue by macc6579** [chengxc/dva-travel#1]
您好，我尝试运行您的代码，安装npm过程顺利；编译过程有报错，
在StackOverflow查看了相关问题，疑似babel版本过低；
但升级最新版本后，依然有同样的问题。
希望能和您一起看下这个问题~~非常感谢
完整报错代码
` Failed to compile. `

` ./node_modules/_history@4.9.0@history/esm/history.js
Module not found: Can't resolve '@babel/runtime/helpers/esm/extends' in '/Users/UserName/dva-travel/node_modules/_history@4.9.0@history/esm' `

**Comment by poozhu** [comment]
https://github.com/dvajs/dva/issues/2032

**Comment by macc6579** [comment]
> [dvajs/dva#2032](https://github.com/dvajs/dva/issues/2032)

谢谢~我把package.json dva配置升级到 ` "dva": "^2.6.0-bata3", `就可以了；
另外还需要安装 babel-polyfill
